create Api tests with library REST Assured
AndreyLatishko/ExampleTestCases pull request #2
Opened 2022-12-04 11:11 UTC by AndreyLatishko

Please  read my code and write comments

2022-12-04 21:22 UTC, yurij-kurleev approved these changes

2022-12-06 22:34 UTC, bfedoronchuk commented on src/test/java/com/tests/helpers/ApiSpecifications.java
> +                .expectStatusCode(Integer.parseInt(String.format("%s",status)))
Why so hard? Integer.parseInt(String.format("%s",status))

2022-12-11 11:41 UTC, bfedoronchuk requested changes

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/api/UnSuccessRegister.java
> +public class UnSuccessRegister {
I'd say rather `Error` than `UnSuccessRegister`, and `error` field -> `message`

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/helpers/ApiSpecifications.java
> +                .expectStatusCode(Integer.parseInt(String.format("%s",status)))
Why so hard? Integer.parseInt(String.format("%s",status))

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/helpers/TestValues.java
> +    private static final String TEST_USER_COMPANYTITLE = "Parimatch Tech";
Just make those constants public, you don't need getters here.

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/example/ReqresTest.java
> +        ApiSpecifications.installSpecification
Is it common to do so? I mean when you depend on some static value it may produce undesirable side effects for tests executed in parallel.

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/helpers/ApiSpecifications.java
> +    public static void installSpecification(RequestSpecification request, ResponseSpecification response){
Why do we need this?

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/api/Register.java
> +public class Register {
Let's rename to `SignupRequest`

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/api/SuccessRegister.java
> +public class SuccessRegister {
`SuccessSignupResponse`?

2022-12-11 11:41 UTC, bfedoronchuk commented on src/test/java/com/tests/api/UserData.java
> +public class UserData {
IMHO Just `User `is fine

2022-12-11 17:17 UTC, AndreyLatishko commented on src/test/java/com/tests/helpers/ApiSpecifications.java
> +    public static void installSpecification(RequestSpecification request, ResponseSpecification response){
> 

To reduce the amount of code. We don't need to assign our request and response to the library in every test. And also in this method we can add a proxy, an aversion via a token, if needed.

2022-12-11 17:24 UTC, AndreyLatishko commented on src/test/java/com/tests/example/ReqresTest.java
> +        ApiSpecifications.installSpecification
Yes, my error. I find best practice and refactoring code

2022-12-28 12:30 UTC, merged